In [1]:
import numpy as np

In [2]:
a = np.arange(5)
b = np.arange(2, 7)

In [11]:
a.sort(ascending = False)

TypeError: 'ascending' is an invalid keyword argument for this function

In [7]:
np.add(a, b)

array([ 2,  4,  6,  8, 10])

In [10]:
a = np.add(a, b)

In [12]:
a.dot(b)

230

In [13]:
a


array([ 4,  7, 10, 13, 16])

In [16]:
# SVD (singular value decomposition)
from numpy.linalg import svd
from numpy.linalg import inv
Z = np.array([[3, 2, 2], [2, 3, -2]])
Y = svd(Z)    
Y   # a tuple of arrays for U, diagonal elements in Sigma and V.T

(array([[-0.70710678, -0.70710678],
        [-0.70710678,  0.70710678]]),
 array([5., 3.]),
 array([[-7.07106781e-01, -7.07106781e-01, -5.55111512e-17],
        [-2.35702260e-01,  2.35702260e-01, -9.42809042e-01],
        [-6.66666667e-01,  6.66666667e-01,  3.33333333e-01]]))

In [17]:
# SVD verification
U, D, Vt = Y
print('Is U orthogonal?')
print(U.T - inv(U))
print('Is Vt orthogonal?')
print(Vt.T - inv(Vt))
print('Are left singular-value vectors orthonormal?')
from numpy.linalg import norm
print(norm(U, axis = 0))
print('Are right singular-value vectors orthonormal?')
print(norm(Vt, axis = 0))
print('SVD?')
Sigma = np.hstack((np.diagflat(D), np.zeros((2, 1))))
print(Z - np.dot(np.dot(U,Sigma), Vt))

Is U orthogonal?
[[-5.55111512e-16 -1.11022302e-16]
 [-3.33066907e-16 -1.11022302e-16]]
Is Vt orthogonal?
[[-3.33066907e-16 -1.38777878e-16  0.00000000e+00]
 [-3.33066907e-16  2.77555756e-17  0.00000000e+00]
 [-5.55111512e-17 -2.22044605e-16 -5.55111512e-17]]
Are left singular-value vectors orthonormal?
[1. 1.]
Are right singular-value vectors orthonormal?
[1. 1. 1.]
SVD?
[[-8.88178420e-16 -8.88178420e-16 -4.44089210e-16]
 [-4.44089210e-16  0.00000000e+00 -6.66133815e-16]]
